# Changes here will be overwritten by Copier
_commit: v0.2.4
_src_path: gh:reservoir-data/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.13'
repository_name: tap-appveyor
repository_namespace: reservoir-data
repository_provider: github.com
repository_visibility: private
tap_auth_method: Bearer Token
tap_id: tap-appveyor
tap_package_command_line_name: tap-appveyor
tap_package_distribution_name: tap-appveyor
tap_package_import_name: tap_appveyor
tap_source_description: Build, test, deploy your apps faster, on any platform.
tap_source_id: AppVeyor
tap_source_name: AppVeyor
tap_stream_type: REST
vscode_files: true
